spring:
  flyway:
    enabled: true
    locations: classpath:db/migration
    url: jdbc:postgresql://localhost:5432/wetrackersyn
    user: postgres
    password: root
    out-of-order: true

  datasource:
    hikari:
      maximum-pool-size: 10
      minimum-idle: 8
    name: WetrackDevelopment
    password: root
    url: jdbc:postgresql://localhost:5432/wetrackersyn
    username: postgres

  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: true
    ddl-auto: validate
    format_sql: true

server:
  port: 8082

logging.level.org.hibernate.SQL: DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder: TRACE

#s3:
#  access-key: AKIA2BKGUXODLOCYYNHQ
#  access-key-secret: 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
#  bucket-name: gf-ig-integration-qa-c0nn3c7
#  region: us-east-1
#  upload:
#    max-backoff-seconds: 300

