
CREATE TABLE UPDATE_NOTIFCATION_NUMBER
(
    ID                BIGSERIAL,
    USER_ID           TEXT,
    NUMBER            TEXT,
    ENABLE_NOTIFY     BOOLEAN,
    TOKEN             TEXT,
    CREATED_AT       TIMESTAMP NOT NULL,
    UPDATED_AT       TIMESTAMP NOT NULL,
    PRIMARY KEY (ID,USER_ID,NUMBER,TOKEN)
);


CREATE INDEX UPDATE_NOTIFCATION_NUMBER_INDEX
    ON UPDATE_NOTIFCATION_NUMBER (USER_ID, NUMBER,TOKEN);












